import React, { useState, useEffect } from 'react';
import { BarChart3, Eye, Download } from 'lucide-react';
import toast from 'react-hot-toast';
import { reportService } from '../../services/reportService';
import Badge from '../../components/common/Badge';
import Table from '../../components/common/Table';
import Modal from '../../components/common/Modal';
import Button from '../../components/common/Button';

const Reports = () => {
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);
  const [filter, setFilter] = useState('all');
  const [isViewOpen, setIsViewOpen] = useState(false);
  const [selectedReport, setSelectedReport] = useState(null);

  useEffect(() => {
    fetchReports();
  }, [filter]);

  const fetchReports = async () => {
    try {
      setLoading(true);
      const params = filter !== 'all' ? { status: filter } : {};
      const response = await reportService.getReports(params);
      setReports(response.reports || []);
    } catch (error) {
      toast.error('Failed to fetch reports');
    } finally {
      setLoading(false);
    }
  };

  const handleView = (report) => {
    setSelectedReport(report);
    setIsViewOpen(true);
  };

  const handleDownload = async (id) => {
    try {
      const blob = await reportService.downloadPDF(id);
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `assessment-report-${id}.pdf`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);
      toast.success('PDF downloaded successfully');
    } catch (error) {
      toast.error('Failed to download PDF');
    }
  };

  const getStatusVariant = (status) => {
    if (status === true || status === 'approved') return 'success';
    if (status === 'rejected') return 'danger';
    return 'warning';
  };

  const getStatusLabel = (row) => {
    if (row.isApproved || row.status === 'approved') return 'APPROVED';
    if (row.status === 'rejected') return 'REJECTED';
    return 'PENDING';
  };

  const tableColumns = [
    {
      key: 'title',
      label: 'Title',
      render: (val, row) => {
        if (val) return val;
        if (row.assessmentId && typeof row.assessmentId === 'object') {
          return `${row.assessmentId.companyName || 'Assessment'} Report`;
        }
        return 'Cybersecurity Audit Report';
      },
    },
    {
      key: 'assessmentId',
      label: 'Assessment',
      render: (val) => {
        if (!val) return 'N/A';
        if (typeof val === 'object') return val.companyName || val._id;
        return val;
      },
    },
    {
      key: 'status',
      label: 'Status',
      render: (_, row) => (
        <Badge variant={getStatusVariant(row.isApproved ? 'approved' : row.status)}>
          {getStatusLabel(row)}
        </Badge>
      ),
    },
    {
      key: 'generatedBy',
      label: 'Generated By',
      render: (val) => (typeof val === 'object' ? val?.name : 'Security Team'),
    },
    {
      key: 'createdAt',
      label: 'Created Date',
      render: (value) => value ? new Date(value).toLocaleDateString() : 'N/A',
    },
    {
      key: 'actions',
      label: 'Actions',
      render: (_, row) => {
        const isApproved = row.isApproved || row.status === 'approved';
        return (
          <div className="flex items-center justify-end space-x-2">
            <button 
              onClick={() => handleView(row)}
              className="text-cyan-400 hover:text-cyan-300 p-1.5 rounded-lg hover:bg-slate-800 transition-colors"
              title="View Details"
            >
              <Eye className="w-4 h-4" />
            </button>
            {isApproved && (
              <button
                onClick={() => handleDownload(row._id)}
                className="text-green-400 hover:text-green-300 p-1.5 rounded-lg hover:bg-slate-800 transition-colors"
                title="Download PDF"
              >
                <Download className="w-4 h-4" />
              </button>
            )}
          </div>
        );
      },
    },
  ];

  return (
    <div>
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 mb-6">
        <div>
          <h1 className="text-2xl font-bold text-white mb-1">My Reports</h1>
          <p className="text-sm text-slate-400">Formal assessment reports and downloadable PDF documentation</p>
        </div>
      </div>

      {/* Filters */}
      <div className="flex flex-wrap gap-2 mb-6">
        {['all', 'pending', 'approved', 'rejected'].map((status) => (
          <button
            key={status}
            onClick={() => setFilter(status)}
            className={`px-4 py-2 rounded-xl transition-colors ${filter === status
              ? 'bg-gradient-to-r from-cyan-500 to-blue-600 text-white font-medium'
              : 'bg-slate-800/50 text-slate-400 hover:text-white border border-slate-700/50'
              }`}
          >
            {status.toUpperCase()}
          </button>
        ))}
      </div>

      {/* Reports Table */}
      <Table
        columns={tableColumns}
        data={reports}
        loading={loading}
        emptyMessage="No reports found"
      />

      {/* View Report Details Modal */}
      <Modal
        isOpen={isViewOpen}
        onClose={() => setIsViewOpen(false)}
        title="Assessment Report View"
        maxWidth="max-w-4xl"
      >
        {selectedReport && (
          <div className="space-y-6">
            <div className="flex items-center justify-between pb-4 border-b border-slate-800">
              <div>
                <h3 className="text-xl font-bold text-white mb-1">
                  {selectedReport.title || 'Cybersecurity Assessment Final Report'}
                </h3>
                <p className="text-xs text-slate-400 font-mono">Report ID: {selectedReport._id}</p>
              </div>
              <Badge variant={getStatusVariant(selectedReport.isApproved ? 'approved' : selectedReport.status)}>
                {getStatusLabel(selectedReport)}
              </Badge>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-4 bg-slate-950/50 p-4 rounded-xl border border-slate-800">
              <div>
                <p className="text-xs text-slate-500">Overall Security Score</p>
                <p className="text-2xl font-bold text-cyan-400">{selectedReport.overallScore || 0} / 100</p>
              </div>
              <div>
                <p className="text-xs text-slate-500">Risk Score</p>
                <p className="text-2xl font-bold text-red-400">{selectedReport.riskScore || 0} / 100</p>
              </div>
              <div>
                <p className="text-xs text-slate-500">Report Date</p>
                <p className="text-sm font-medium text-white mt-1">
                  {selectedReport.createdAt ? new Date(selectedReport.createdAt).toLocaleDateString() : 'N/A'}
                </p>
              </div>
            </div>

            <div>
              <h4 className="text-sm font-semibold text-cyan-400 uppercase tracking-wider mb-2">Executive Summary</h4>
              <p className="text-sm text-slate-300 bg-slate-950/50 p-4 rounded-xl border border-slate-800 whitespace-pre-wrap">
                {selectedReport.executiveSummary}
              </p>
            </div>

            {selectedReport.findings && selectedReport.findings.length > 0 && (
              <div>
                <h4 className="text-sm font-semibold text-cyan-400 uppercase tracking-wider mb-2">Key Findings Summary</h4>
                <div className="space-y-2">
                  {selectedReport.findings.map((f, idx) => (
                    <div key={idx} className="flex justify-between items-center bg-slate-950/50 p-3 rounded-lg border border-slate-800">
                      <div>
                        <p className="text-sm font-semibold text-white">{f.category}</p>
                        <p className="text-xs text-slate-400">{f.description}</p>
                      </div>
                      <Badge variant={f.severity === 'critical' || f.severity === 'high' ? 'danger' : 'info'}>
                        {f.severity ? f.severity.toUpperCase() : 'INFO'}
                      </Badge>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {selectedReport.recommendations && selectedReport.recommendations.length > 0 && (
              <div>
                <h4 className="text-sm font-semibold text-green-400 uppercase tracking-wider mb-2">Recommendations</h4>
                <div className="space-y-2">
                  {selectedReport.recommendations.map((r, idx) => (
                    <div key={idx} className="bg-slate-950/50 p-3 rounded-lg border border-slate-800">
                      <div className="flex justify-between items-center mb-1">
                        <span className="text-sm font-semibold text-white">{r.title}</span>
                        <span className="text-xs font-medium text-slate-400">Effort: {r.estimatedEffort || 'N/A'}</span>
                      </div>
                      <p className="text-xs text-slate-400">{r.description}</p>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {selectedReport.conclusion && (
              <div>
                <h4 className="text-sm font-semibold text-cyan-400 uppercase tracking-wider mb-2">Conclusion & Next Steps</h4>
                <p className="text-sm text-slate-300 bg-slate-950/50 p-4 rounded-xl border border-slate-800 whitespace-pre-wrap">
                  {selectedReport.conclusion}
                </p>
              </div>
            )}

            <div className="flex justify-end space-x-3 pt-4 border-t border-slate-800">
              <Button variant="secondary" onClick={() => setIsViewOpen(false)}>
                Close
              </Button>
              {(selectedReport.isApproved || selectedReport.status === 'approved') && (
                <Button icon={Download} onClick={() => handleDownload(selectedReport._id)}>
                  Download PDF
                </Button>
              )}
            </div>
          </div>
        )}
      </Modal>
    </div>
  );
};

export default Reports;
