const mongoose = require('mongoose');


const reportSchema = new mongoose.Schema(
  {
    assessmentId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Assessment',
      required: [true, 'Assessment is required'],
      unique: true,
      index: true,
    },
    title: {
      type: String,
      trim: true,
      default: 'Cybersecurity Assessment Report',
    },
    status: {
      type: String,
      enum: ['pending', 'approved', 'rejected'],
      default: 'pending',
      index: true,
    },
    rejectionReason: {
      type: String,
      trim: true,
    },
    executiveSummary: {
      type: String,
      required: [true, 'Executive summary is required'],
      trim: true,
      maxlength: [10000, 'Executive summary cannot exceed 10000 characters'],
    },
    findings: [{
      category: {
        type: String,
        required: true,
        trim: true,
      },
      description: {
        type: String,
        required: true,
        trim: true,
      },
      severity: {
        type: String,
        enum: ['critical', 'high', 'medium', 'low', 'info'],
        required: true,
      },
      count: {
        type: Number,
        default: 1,
      },
    }],
    riskScore: {
      type: Number,
      required: [true, 'Risk score is required'],
      min: [0, 'Risk score must be between 0 and 100'],
      max: [100, 'Risk score must be between 0 and 100'],
    },
    recommendations: [{
      priority: {
        type: String,
        enum: ['critical', 'high', 'medium', 'low'],
        required: true,
      },
      title: {
        type: String,
        required: true,
        trim: true,
      },
      description: {
        type: String,
        required: true,
        trim: true,
      },
      estimatedEffort: {
        type: String,
        trim: true,
      },
    }],
    vulnerabilityList: [{
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Vulnerability',
    }],
    overallScore: {
      type: Number,
      required: [true, 'Overall score is required'],
      min: [0, 'Overall score must be between 0 and 100'],
      max: [100, 'Overall score must be between 0 and 100'],
    },
    methodology: {
      type: String,
      trim: true,
      maxlength: [5000, 'Methodology cannot exceed 5000 characters'],
    },
    scope: {
      type: String,
      trim: true,
      maxlength: [2000, 'Scope cannot exceed 2000 characters'],
    },
    limitations: {
      type: String,
      trim: true,
      maxlength: [2000, 'Limitations cannot exceed 2000 characters'],
    },
    conclusion: {
      type: String,
      trim: true,
      maxlength: [5000, 'Conclusion cannot exceed 5000 characters'],
    },
    generatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: [true, 'Generated by is required'],
    },
    approvedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    approvedDate: {
      type: Date,
    },
    isApproved: {
      type: Boolean,
      default: false,
    },
    version: {
      type: String,
      default: '1.0',
    },
    // Metadata for tracking
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    updatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
  },
  {
    timestamps: true,
  }
);


reportSchema.index({ assessmentId: 1 });
reportSchema.index({ generatedBy: 1 });
reportSchema.index({ isApproved: 1 });
reportSchema.index({ createdAt: -1 });


reportSchema.virtual('vulnerabilityCounts').get(function () {
  const counts = {
    critical: 0,
    high: 0,
    medium: 0,
    low: 0,
    info: 0,
    total: 0,
  };
  
  this.findings.forEach((finding) => {
    if (counts.hasOwnProperty(finding.severity)) {
      counts[finding.severity] += finding.count || 1;
      counts.total += finding.count || 1;
    }
  });
  
  return counts;
});


reportSchema.virtual('approvalStatus').get(function () {
  return this.isApproved ? 'Approved' : 'Pending Approval';
});

// Ensure virtuals are included in JSON
reportSchema.set('toJSON', { virtuals: true });
reportSchema.set('toObject', { virtuals: true });

module.exports = mongoose.model('Report', reportSchema);
